import React from "react";
import { notFound } from "next/navigation";
import { prisma } from "@webbing/db";
import { CheckCircle2, Mail } from "lucide-react";

export default async function GeneratedSitePage({ params }: { params: { subdomain: string; path?: string[] } }) {
  const slug = params.path?.join("/") || "index";
  const project = await prisma.project.findUnique({
    where: { subdomain: params.subdomain },
    include: { pages: { include: { sections: { orderBy: { order: "asc" } } } } },
  });

  if (!project) notFound();

  const page = project.pages.find((item) => item.slug === slug) || project.pages.find((item) => item.slug === "index") || project.pages[0];
  if (!page) notFound();

  const hero = page.sections.find((section) => section.type === "HERO")?.content as any;
  const features = page.sections.find((section) => section.type === "FEATURES")?.content as any;
  const items = Array.isArray(features?.items) ? features.items : [
    { title: "Fast launch", description: "A polished web presence generated from your business details." },
    { title: "Clear messaging", description: "Concise sections for value, proof, pricing, and contact." },
    { title: "Responsive layout", description: "A modern dark-first visual system for desktop and mobile." },
  ];

  return (
    <div className="site-preview">
      <main>
        <section className="preview-hero">
          <div>
            <span className="eyebrow">{project.name}</span>
            <h1>{hero?.heading || page.title}</h1>
            <p style={{ color: "#b8c3d4", fontSize: "1.1rem" }}>{hero?.subheading || page.description || project.description}</p>
            <a className="primary-action" href={hero?.ctaUrl || "#contact"}>{hero?.ctaText || "Contact us"}</a>
          </div>
          <aside className="preview-panel">
            <strong>Now live</strong>
            <p style={{ color: "#b8c3d4" }}>Generated by Webbing with a modern responsive theme.</p>
            <div className="key-meta">
              <span>{project.status}</span>
              <span>{params.subdomain}</span>
            </div>
          </aside>
        </section>

        <section style={{ padding: "4rem 0" }}>
          <div className="feature-grid">
            {items.slice(0, 3).map((item: any, index: number) => (
              <article className="feature-card" key={`${item.title}-${index}`}>
                <span className="icon-box"><CheckCircle2 size={20} /></span>
                <h3>{item.title}</h3>
                <p>{item.description}</p>
              </article>
            ))}
          </div>
        </section>

        <section id="contact" className="preview-panel">
          <span className="eyebrow"><Mail size={14} /> Contact</span>
          <h2>Let’s talk about your next project.</h2>
          <p style={{ color: "#b8c3d4" }}>This generated site includes a contact-ready section and can be expanded with custom pages, products, or domain setup.</p>
          <a className="secondary-action" href="mailto:hello@example.com">hello@example.com</a>
        </section>
      </main>
    </div>
  );
}
