import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { prisma } from "@webbing/db";
import { verifySession } from "@/lib/session";
import { generateCustomLicenseKey } from "@/lib/licensing";

export async function POST(req: Request) {
  try {
    const cookieStore = cookies();
    const sessionToken = cookieStore.get("webbing-session")?.value;
    const user = sessionToken ? verifySession(sessionToken) : null;

    if (!user || user.role !== "ADMIN") {
      return NextResponse.json({ error: "Unauthorized. Admin privileges required." }, { status: 401 });
    }

    const key = generateCustomLicenseKey();

    // Save generated key to the central licensing table
    const newLicense = await prisma.centralLicense.create({
      data: {
        licenseKey: key,
        status: "ACTIVE",
        type: "CUSTOM",
        notes: `Generated by Admin: ${user.email}`,
      },
    });

    return NextResponse.json({
      success: true,
      licenseKey: newLicense.licenseKey,
    });
  } catch (error: any) {
    console.error("POST Admin Licensing Generator Exception:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
